<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYMINW0635" ignored="13" name="Tests of arithmetic function with Double aruments" tests="34" failures="3" timestamp="02 Oct 2018 07:08:12 GMT" time="0.125" errors="0">
  <testcase name="divDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv"/>
  <testcase name="divDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv"/>
  <testcase name="divDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv"/>
  <testcase name="divDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv"/>
  <testcase name="divDoubleTest" time="0.015" classname="com.epam.tat.calctest.testng.TstDiv"/>
  <testcase name="divDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv"/>
  <testcase name="divDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv"/>
  <testcase name="divDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv"/>
  <testcase name="multDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstMult"/>
  <testcase name="multDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstMult"/>
  <testcase name="multDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstMult"/>
  <testcase name="multDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstMult"/>
  <testcase name="multDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstMult"/>
  <testcase name="multDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstMult">
    <failure type="java.lang.AssertionError" message="Invalid result expected [16.0115] but found [16.0]">
      <![CDATA[java.lang.AssertionError: Invalid result expected [16.0115] but found [16.0]
at com.epam.tat.calctest.testng.TstMult.multDoubleTest(TstMult.java:24)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- multDoubleTest -->
  <testcase name="powTest" time="0.0" classname="com.epam.tat.calctest.testng.TstPow"/>
  <testcase name="powTest" time="0.0" classname="com.epam.tat.calctest.testng.TstPow"/>
  <testcase name="powTest" time="0.0" classname="com.epam.tat.calctest.testng.TstPow"/>
  <testcase name="powTest" time="0.0" classname="com.epam.tat.calctest.testng.TstPow"/>
  <testcase name="powTest" time="0.0" classname="com.epam.tat.calctest.testng.TstPow"/>
  <testcase name="powTest" time="0.0" classname="com.epam.tat.calctest.testng.TstPow">
    <failure type="java.lang.AssertionError" message="Invalid result expected [11.211578456539659] but found [9.0]">
      <![CDATA[java.lang.AssertionError: Invalid result expected [11.211578456539659] but found [9.0]
at com.epam.tat.calctest.testng.TstPow.powTest(TstPow.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- powTest -->
  <testcase name="sqrtTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSqrt"/>
  <testcase name="sqrtTest" time="0.016" classname="com.epam.tat.calctest.testng.TstSqrt"/>
  <testcase name="sqrtTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSqrt"/>
  <testcase name="sqrtTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSqrt"/>
  <testcase name="sqrtTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSqrt"/>
  <testcase name="sqrtTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSqrt">
    <failure type="java.lang.AssertionError" message="Invalid result expected [NaN] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Invalid result expected [NaN] but found [1.0]
at com.epam.tat.calctest.testng.TstSqrt.sqrtTest(TstSqrt.java:21)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sqrtTest -->
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSub"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSub"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSub"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSub"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSum"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSum"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSum"/>
  <testcase name="sumDoubleTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSum"/>
  <testcase name="sumLongTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSum">
    <ignored/>
  </testcase> <!-- sumLongTest -->
  <testcase name="tgTest" time="0.0" classname="com.epam.tat.calctest.testng.TstTg">
    <ignored/>
  </testcase> <!-- tgTest -->
  <testcase name="sinTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSin">
    <ignored/>
  </testcase> <!-- sinTest -->
  <testcase name="common" time="0.0" classname="com.epam.tat.calctest.testng.CommonTest">
    <ignored/>
  </testcase> <!-- common -->
  <testcase name="cosTest" time="0.0" classname="com.epam.tat.calctest.testng.TstCos">
    <ignored/>
  </testcase> <!-- cosTest -->
  <testcase name="ctgTest" time="0.0" classname="com.epam.tat.calctest.testng.TstCtg">
    <ignored/>
  </testcase> <!-- ctgTest -->
  <testcase name="isNegativeTest" time="0.0" classname="com.epam.tat.calctest.testng.TstIsNegative">
    <ignored/>
  </testcase> <!-- isNegativeTest -->
  <testcase name="divLongDivByZeroTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv">
    <ignored/>
  </testcase> <!-- divLongDivByZeroTest -->
  <testcase name="multLongTest" time="0.0" classname="com.epam.tat.calctest.testng.TstMult">
    <ignored/>
  </testcase> <!-- multLongTest -->
  <testcase name="isPositiveTest" time="0.0" classname="com.epam.tat.calctest.testng.TstIsPositive">
    <ignored/>
  </testcase> <!-- isPositiveTest -->
  <testcase name="divLongTest" time="0.0" classname="com.epam.tat.calctest.testng.TstDiv">
    <ignored/>
  </testcase> <!-- divLongTest -->
  <testcase name="negativeArgumentTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSqrt">
    <ignored/>
  </testcase> <!-- negativeArgumentTest -->
  <testcase name="sumLongTest" time="0.0" classname="com.epam.tat.calctest.testng.TstSub">
    <ignored/>
  </testcase> <!-- sumLongTest -->
</testsuite> <!-- Tests of arithmetic function with Double aruments -->
