<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite thread-count="3" guice-stage="DEVELOPMENT" name="Failed suite [Calculator test suite]" parallel="tests">
  <test thread-count="3" name="Tests of arithmetic function with Double aruments(failed)" parallel="tests">
    <groups>
      <run>
        <include name="doubleInputData"/>
        <exclude name="trigonometric"/>
      </run>
    </groups>
    <classes>
      <class name="com.epam.tat.calctest.testng.TstMult">
        <methods>
          <include name="setUp"/>
          <include name="multDoubleTest" invocation-numbers="5"/>
        </methods>
      </class> <!-- com.epam.tat.calctest.testng.TstMult -->
      <class name="com.epam.tat.calctest.testng.TstPow">
        <methods>
          <include name="powTest" invocation-numbers="5"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.epam.tat.calctest.testng.TstPow -->
      <class name="com.epam.tat.calctest.testng.TstSqrt">
        <methods>
          <include name="sqrtTest" invocation-numbers="5"/>
          <include name="setUp"/>
        </methods>
      </class> <!-- com.epam.tat.calctest.testng.TstSqrt -->
    </classes>
  </test> <!-- Tests of arithmetic function with Double aruments(failed) -->
</suite> <!-- Failed suite [Calculator test suite] -->
