<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ZenBook" ignored="12" name="Tests of arithmetic function with Double aruments" tests="34" failures="3" timestamp="02 окт 2018 19:25:59 GMT" time="0.219" errors="0">
  <testcase name="divDoubleTest" time="0.005" classname="com.epam.tat.calctest.testng.DivTest"/>
  <testcase name="divDoubleTest" time="0.004" classname="com.epam.tat.calctest.testng.DivTest"/>
  <testcase name="divDoubleTest" time="0.001" classname="com.epam.tat.calctest.testng.DivTest"/>
  <testcase name="divDoubleTest" time="0.001" classname="com.epam.tat.calctest.testng.DivTest"/>
  <testcase name="divDoubleTest" time="0.001" classname="com.epam.tat.calctest.testng.DivTest"/>
  <testcase name="divDoubleTest" time="0.002" classname="com.epam.tat.calctest.testng.DivTest"/>
  <testcase name="divDoubleTest" time="0.002" classname="com.epam.tat.calctest.testng.DivTest"/>
  <testcase name="divDoubleTest" time="0.002" classname="com.epam.tat.calctest.testng.DivTest"/>
  <testcase name="multDoubleTest" time="0.005" classname="com.epam.tat.calctest.testng.MultTest"/>
  <testcase name="multDoubleTest" time="0.002" classname="com.epam.tat.calctest.testng.MultTest"/>
  <testcase name="multDoubleTest" time="0.001" classname="com.epam.tat.calctest.testng.MultTest"/>
  <testcase name="multDoubleTest" time="0.002" classname="com.epam.tat.calctest.testng.MultTest"/>
  <testcase name="multDoubleTest" time="0.002" classname="com.epam.tat.calctest.testng.MultTest"/>
  <testcase name="multDoubleTest" time="0.004" classname="com.epam.tat.calctest.testng.MultTest">
    <failure type="java.lang.AssertionError" message="Invalid result expected [16.0115] but found [16.0]">
      <![CDATA[java.lang.AssertionError: Invalid result expected [16.0115] but found [16.0]
at com.epam.tat.calctest.testng.MultTest.multDoubleTest(MultTest.java:24)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- multDoubleTest -->
  <testcase name="powTest" time="0.002" classname="com.epam.tat.calctest.testng.PowTest"/>
  <testcase name="powTest" time="0.002" classname="com.epam.tat.calctest.testng.PowTest"/>
  <testcase name="powTest" time="0.001" classname="com.epam.tat.calctest.testng.PowTest"/>
  <testcase name="powTest" time="0.001" classname="com.epam.tat.calctest.testng.PowTest"/>
  <testcase name="powTest" time="0.0" classname="com.epam.tat.calctest.testng.PowTest"/>
  <testcase name="powTest" time="0.002" classname="com.epam.tat.calctest.testng.PowTest">
    <failure type="java.lang.AssertionError" message="Invalid result expected [11.211578456539659] but found [9.0]">
      <![CDATA[java.lang.AssertionError: Invalid result expected [11.211578456539659] but found [9.0]
at com.epam.tat.calctest.testng.PowTest.powTest(PowTest.java:14)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- powTest -->
  <testcase name="sqrtTest" time="0.007" classname="com.epam.tat.calctest.testng.SqrtTest"/>
  <testcase name="sqrtTest" time="0.004" classname="com.epam.tat.calctest.testng.SqrtTest"/>
  <testcase name="sqrtTest" time="0.001" classname="com.epam.tat.calctest.testng.SqrtTest"/>
  <testcase name="sqrtTest" time="0.002" classname="com.epam.tat.calctest.testng.SqrtTest"/>
  <testcase name="sqrtTest" time="0.0" classname="com.epam.tat.calctest.testng.SqrtTest"/>
  <testcase name="sqrtTest" time="0.002" classname="com.epam.tat.calctest.testng.SqrtTest">
    <failure type="java.lang.AssertionError" message="Invalid result expected [NaN] but found [1.0]">
      <![CDATA[java.lang.AssertionError: Invalid result expected [NaN] but found [1.0]
at com.epam.tat.calctest.testng.SqrtTest.sqrtTest(SqrtTest.java:21)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sqrtTest -->
  <testcase name="sumDoubleTest" time="0.001" classname="com.epam.tat.calctest.testng.SubTest"/>
  <testcase name="sumDoubleTest" time="0.001" classname="com.epam.tat.calctest.testng.SubTest"/>
  <testcase name="sumDoubleTest" time="0.001" classname="com.epam.tat.calctest.testng.SubTest"/>
  <testcase name="sumDoubleTest" time="0.003" classname="com.epam.tat.calctest.testng.SubTest"/>
  <testcase name="sumDoubleTest" time="0.004" classname="com.epam.tat.calctest.testng.SumTest"/>
  <testcase name="sumDoubleTest" time="0.001" classname="com.epam.tat.calctest.testng.SumTest"/>
  <testcase name="sumDoubleTest" time="0.003" classname="com.epam.tat.calctest.testng.SumTest"/>
  <testcase name="sumDoubleTest" time="0.002" classname="com.epam.tat.calctest.testng.SumTest"/>
  <testcase name="ctgTest" time="0.0" classname="com.epam.tat.calctest.testng.CtgTest">
    <ignored/>
  </testcase> <!-- ctgTest -->
  <testcase name="multLongTest" time="0.0" classname="com.epam.tat.calctest.testng.MultTest">
    <ignored/>
  </testcase> <!-- multLongTest -->
  <testcase name="cosTest" time="0.0" classname="com.epam.tat.calctest.testng.CosTest">
    <ignored/>
  </testcase> <!-- cosTest -->
  <testcase name="sumLongTest" time="0.0" classname="com.epam.tat.calctest.testng.SubTest">
    <ignored/>
  </testcase> <!-- sumLongTest -->
  <testcase name="divLongTest" time="0.0" classname="com.epam.tat.calctest.testng.DivTest">
    <ignored/>
  </testcase> <!-- divLongTest -->
  <testcase name="isNegativeTest" time="0.0" classname="com.epam.tat.calctest.testng.IsNegativeTest">
    <ignored/>
  </testcase> <!-- isNegativeTest -->
  <testcase name="sumLongTest" time="0.0" classname="com.epam.tat.calctest.testng.SumTest">
    <ignored/>
  </testcase> <!-- sumLongTest -->
  <testcase name="isPositiveTest" time="0.0" classname="com.epam.tat.calctest.testng.IsPositiveTest">
    <ignored/>
  </testcase> <!-- isPositiveTest -->
  <testcase name="divLongDivByZeroTest" time="0.0" classname="com.epam.tat.calctest.testng.DivTest">
    <ignored/>
  </testcase> <!-- divLongDivByZeroTest -->
  <testcase name="negativeArgumentTest" time="0.0" classname="com.epam.tat.calctest.testng.SqrtTest">
    <ignored/>
  </testcase> <!-- negativeArgumentTest -->
  <testcase name="sinTest" time="0.0" classname="com.epam.tat.calctest.testng.SinTest">
    <ignored/>
  </testcase> <!-- sinTest -->
  <testcase name="tgTest" time="0.0" classname="com.epam.tat.calctest.testng.TgTest">
    <ignored/>
  </testcase> <!-- tgTest -->
</testsuite> <!-- Tests of arithmetic function with Double aruments -->
